//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("foodModel", "FK_Ingredients_In_Meals_Ingredients", "Ingredients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WeightLoss.Ingredient), "Ingredients_In_Meals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WeightLoss.Ingredients_In_Meals), true)]
[assembly: EdmRelationshipAttribute("foodModel", "FK_Meals_Ingredients_In_Meals", "Meals", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WeightLoss.Meal), "Ingredients_In_Meals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WeightLoss.Ingredients_In_Meals), true)]
[assembly: EdmRelationshipAttribute("foodModel", "FK_Users_MealPlanList", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WeightLoss.User), "MealPlanList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WeightLoss.MealPlanList), true)]
[assembly: EdmRelationshipAttribute("foodModel", "FK_Users_Meals", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WeightLoss.User), "Meals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WeightLoss.Meal), true)]

#endregion

namespace WeightLoss
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class foodEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new foodEntities object using the connection string found in the 'foodEntities' section of the application configuration file.
        /// </summary>
        public foodEntities() : base("name=foodEntities", "foodEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new foodEntities object.
        /// </summary>
        public foodEntities(string connectionString) : base(connectionString, "foodEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new foodEntities object.
        /// </summary>
        public foodEntities(EntityConnection connection) : base(connection, "foodEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingredient> Ingredients
        {
            get
            {
                if ((_Ingredients == null))
                {
                    _Ingredients = base.CreateObjectSet<Ingredient>("Ingredients");
                }
                return _Ingredients;
            }
        }
        private ObjectSet<Ingredient> _Ingredients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingredients_In_Meals> Ingredients_In_Meals
        {
            get
            {
                if ((_Ingredients_In_Meals == null))
                {
                    _Ingredients_In_Meals = base.CreateObjectSet<Ingredients_In_Meals>("Ingredients_In_Meals");
                }
                return _Ingredients_In_Meals;
            }
        }
        private ObjectSet<Ingredients_In_Meals> _Ingredients_In_Meals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MealPlanList> MealPlanLists
        {
            get
            {
                if ((_MealPlanLists == null))
                {
                    _MealPlanLists = base.CreateObjectSet<MealPlanList>("MealPlanLists");
                }
                return _MealPlanLists;
            }
        }
        private ObjectSet<MealPlanList> _MealPlanLists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Meal> Meals
        {
            get
            {
                if ((_Meals == null))
                {
                    _Meals = base.CreateObjectSet<Meal>("Meals");
                }
                return _Meals;
            }
        }
        private ObjectSet<Meal> _Meals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredients(Ingredient ingredient)
        {
            base.AddObject("Ingredients", ingredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredients_In_Meals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredients_In_Meals(Ingredients_In_Meals ingredients_In_Meals)
        {
            base.AddObject("Ingredients_In_Meals", ingredients_In_Meals);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MealPlanLists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMealPlanLists(MealPlanList mealPlanList)
        {
            base.AddObject("MealPlanLists", mealPlanList);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Meals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMeals(Meal meal)
        {
            base.AddObject("Meals", meal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodModel", Name="Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingredient object.
        /// </summary>
        /// <param name="ingredientId">Initial value of the IngredientId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="quantity_Nbr">Initial value of the Quantity_Nbr property.</param>
        /// <param name="quantity_Measurement">Initial value of the Quantity_Measurement property.</param>
        public static Ingredient CreateIngredient(global::System.Int32 ingredientId, global::System.String name, global::System.Decimal quantity_Nbr, global::System.String quantity_Measurement)
        {
            Ingredient ingredient = new Ingredient();
            ingredient.IngredientId = ingredientId;
            ingredient.Name = name;
            ingredient.Quantity_Nbr = quantity_Nbr;
            ingredient.Quantity_Measurement = quantity_Measurement;
            return ingredient;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientId
        {
            get
            {
                return _IngredientId;
            }
            set
            {
                if (_IngredientId != value)
                {
                    OnIngredientIdChanging(value);
                    ReportPropertyChanging("IngredientId");
                    _IngredientId = StructuralObject.SetValidValue(value, "IngredientId");
                    ReportPropertyChanged("IngredientId");
                    OnIngredientIdChanged();
                }
            }
        }
        private global::System.Int32 _IngredientId;
        partial void OnIngredientIdChanging(global::System.Int32 value);
        partial void OnIngredientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Quantity_Nbr
        {
            get
            {
                return _Quantity_Nbr;
            }
            set
            {
                OnQuantity_NbrChanging(value);
                ReportPropertyChanging("Quantity_Nbr");
                _Quantity_Nbr = StructuralObject.SetValidValue(value, "Quantity_Nbr");
                ReportPropertyChanged("Quantity_Nbr");
                OnQuantity_NbrChanged();
            }
        }
        private global::System.Decimal _Quantity_Nbr;
        partial void OnQuantity_NbrChanging(global::System.Decimal value);
        partial void OnQuantity_NbrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Quantity_Measurement
        {
            get
            {
                return _Quantity_Measurement;
            }
            set
            {
                OnQuantity_MeasurementChanging(value);
                ReportPropertyChanging("Quantity_Measurement");
                _Quantity_Measurement = StructuralObject.SetValidValue(value, false, "Quantity_Measurement");
                ReportPropertyChanged("Quantity_Measurement");
                OnQuantity_MeasurementChanged();
            }
        }
        private global::System.String _Quantity_Measurement;
        partial void OnQuantity_MeasurementChanging(global::System.String value);
        partial void OnQuantity_MeasurementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Calories
        {
            get
            {
                return _Calories;
            }
            set
            {
                OnCaloriesChanging(value);
                ReportPropertyChanging("Calories");
                _Calories = StructuralObject.SetValidValue(value, "Calories");
                ReportPropertyChanged("Calories");
                OnCaloriesChanged();
            }
        }
        private Nullable<global::System.Int16> _Calories;
        partial void OnCaloriesChanging(Nullable<global::System.Int16> value);
        partial void OnCaloriesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true, "Category");
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodModel", "FK_Ingredients_In_Meals_Ingredients", "Ingredients_In_Meals")]
        public EntityCollection<Ingredients_In_Meals> Ingredients_In_Meals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingredients_In_Meals>("foodModel.FK_Ingredients_In_Meals_Ingredients", "Ingredients_In_Meals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingredients_In_Meals>("foodModel.FK_Ingredients_In_Meals_Ingredients", "Ingredients_In_Meals", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodModel", Name="Ingredients_In_Meals")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredients_In_Meals : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingredients_In_Meals object.
        /// </summary>
        /// <param name="instanceId">Initial value of the InstanceId property.</param>
        /// <param name="mealId">Initial value of the MealId property.</param>
        /// <param name="ingredientId">Initial value of the IngredientId property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        public static Ingredients_In_Meals CreateIngredients_In_Meals(global::System.Int32 instanceId, global::System.Int32 mealId, global::System.Int32 ingredientId, global::System.Int16 quantity)
        {
            Ingredients_In_Meals ingredients_In_Meals = new Ingredients_In_Meals();
            ingredients_In_Meals.InstanceId = instanceId;
            ingredients_In_Meals.MealId = mealId;
            ingredients_In_Meals.IngredientId = ingredientId;
            ingredients_In_Meals.Quantity = quantity;
            return ingredients_In_Meals;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InstanceId
        {
            get
            {
                return _InstanceId;
            }
            set
            {
                if (_InstanceId != value)
                {
                    OnInstanceIdChanging(value);
                    ReportPropertyChanging("InstanceId");
                    _InstanceId = StructuralObject.SetValidValue(value, "InstanceId");
                    ReportPropertyChanged("InstanceId");
                    OnInstanceIdChanged();
                }
            }
        }
        private global::System.Int32 _InstanceId;
        partial void OnInstanceIdChanging(global::System.Int32 value);
        partial void OnInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MealId
        {
            get
            {
                return _MealId;
            }
            set
            {
                OnMealIdChanging(value);
                ReportPropertyChanging("MealId");
                _MealId = StructuralObject.SetValidValue(value, "MealId");
                ReportPropertyChanged("MealId");
                OnMealIdChanged();
            }
        }
        private global::System.Int32 _MealId;
        partial void OnMealIdChanging(global::System.Int32 value);
        partial void OnMealIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientId
        {
            get
            {
                return _IngredientId;
            }
            set
            {
                OnIngredientIdChanging(value);
                ReportPropertyChanging("IngredientId");
                _IngredientId = StructuralObject.SetValidValue(value, "IngredientId");
                ReportPropertyChanged("IngredientId");
                OnIngredientIdChanged();
            }
        }
        private global::System.Int32 _IngredientId;
        partial void OnIngredientIdChanging(global::System.Int32 value);
        partial void OnIngredientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value, "Quantity");
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Int16 _Quantity;
        partial void OnQuantityChanging(global::System.Int16 value);
        partial void OnQuantityChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodModel", "FK_Ingredients_In_Meals_Ingredients", "Ingredients")]
        public Ingredient Ingredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("foodModel.FK_Ingredients_In_Meals_Ingredients", "Ingredients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("foodModel.FK_Ingredients_In_Meals_Ingredients", "Ingredients").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ingredient> IngredientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("foodModel.FK_Ingredients_In_Meals_Ingredients", "Ingredients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ingredient>("foodModel.FK_Ingredients_In_Meals_Ingredients", "Ingredients", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodModel", "FK_Meals_Ingredients_In_Meals", "Meals")]
        public Meal Meal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meal>("foodModel.FK_Meals_Ingredients_In_Meals", "Meals").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meal>("foodModel.FK_Meals_Ingredients_In_Meals", "Meals").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Meal> MealReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meal>("foodModel.FK_Meals_Ingredients_In_Meals", "Meals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Meal>("foodModel.FK_Meals_Ingredients_In_Meals", "Meals", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodModel", Name="Meal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Meal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Meal object.
        /// </summary>
        /// <param name="mealId">Initial value of the MealId property.</param>
        /// <param name="breakfast">Initial value of the Breakfast property.</param>
        /// <param name="lunch">Initial value of the Lunch property.</param>
        /// <param name="dinner">Initial value of the Dinner property.</param>
        /// <param name="snack">Initial value of the Snack property.</param>
        public static Meal CreateMeal(global::System.Int32 mealId, global::System.Boolean breakfast, global::System.Boolean lunch, global::System.Boolean dinner, global::System.Boolean snack)
        {
            Meal meal = new Meal();
            meal.MealId = mealId;
            meal.Breakfast = breakfast;
            meal.Lunch = lunch;
            meal.Dinner = dinner;
            meal.Snack = snack;
            return meal;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MealId
        {
            get
            {
                return _MealId;
            }
            set
            {
                if (_MealId != value)
                {
                    OnMealIdChanging(value);
                    ReportPropertyChanging("MealId");
                    _MealId = StructuralObject.SetValidValue(value, "MealId");
                    ReportPropertyChanged("MealId");
                    OnMealIdChanged();
                }
            }
        }
        private global::System.Int32 _MealId;
        partial void OnMealIdChanging(global::System.Int32 value);
        partial void OnMealIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cuisine
        {
            get
            {
                return _Cuisine;
            }
            set
            {
                OnCuisineChanging(value);
                ReportPropertyChanging("Cuisine");
                _Cuisine = StructuralObject.SetValidValue(value, true, "Cuisine");
                ReportPropertyChanged("Cuisine");
                OnCuisineChanged();
            }
        }
        private global::System.String _Cuisine;
        partial void OnCuisineChanging(global::System.String value);
        partial void OnCuisineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Breakfast
        {
            get
            {
                return _Breakfast;
            }
            set
            {
                OnBreakfastChanging(value);
                ReportPropertyChanging("Breakfast");
                _Breakfast = StructuralObject.SetValidValue(value, "Breakfast");
                ReportPropertyChanged("Breakfast");
                OnBreakfastChanged();
            }
        }
        private global::System.Boolean _Breakfast;
        partial void OnBreakfastChanging(global::System.Boolean value);
        partial void OnBreakfastChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Lunch
        {
            get
            {
                return _Lunch;
            }
            set
            {
                OnLunchChanging(value);
                ReportPropertyChanging("Lunch");
                _Lunch = StructuralObject.SetValidValue(value, "Lunch");
                ReportPropertyChanged("Lunch");
                OnLunchChanged();
            }
        }
        private global::System.Boolean _Lunch;
        partial void OnLunchChanging(global::System.Boolean value);
        partial void OnLunchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Dinner
        {
            get
            {
                return _Dinner;
            }
            set
            {
                OnDinnerChanging(value);
                ReportPropertyChanging("Dinner");
                _Dinner = StructuralObject.SetValidValue(value, "Dinner");
                ReportPropertyChanged("Dinner");
                OnDinnerChanged();
            }
        }
        private global::System.Boolean _Dinner;
        partial void OnDinnerChanging(global::System.Boolean value);
        partial void OnDinnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Snack
        {
            get
            {
                return _Snack;
            }
            set
            {
                OnSnackChanging(value);
                ReportPropertyChanging("Snack");
                _Snack = StructuralObject.SetValidValue(value, "Snack");
                ReportPropertyChanged("Snack");
                OnSnackChanged();
            }
        }
        private global::System.Boolean _Snack;
        partial void OnSnackChanging(global::System.Boolean value);
        partial void OnSnackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Rating
        {
            get
            {
                return _Rating;
            }
            set
            {
                OnRatingChanging(value);
                ReportPropertyChanging("Rating");
                _Rating = StructuralObject.SetValidValue(value, "Rating");
                ReportPropertyChanged("Rating");
                OnRatingChanged();
            }
        }
        private Nullable<global::System.Byte> _Rating;
        partial void OnRatingChanging(Nullable<global::System.Byte> value);
        partial void OnRatingChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodModel", "FK_Meals_Ingredients_In_Meals", "Ingredients_In_Meals")]
        public EntityCollection<Ingredients_In_Meals> Ingredients_In_Meals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingredients_In_Meals>("foodModel.FK_Meals_Ingredients_In_Meals", "Ingredients_In_Meals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingredients_In_Meals>("foodModel.FK_Meals_Ingredients_In_Meals", "Ingredients_In_Meals", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodModel", "FK_Users_Meals", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("foodModel.FK_Users_Meals", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("foodModel.FK_Users_Meals", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("foodModel.FK_Users_Meals", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("foodModel.FK_Users_Meals", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodModel", Name="MealPlanList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MealPlanList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MealPlanList object.
        /// </summary>
        /// <param name="instanceId">Initial value of the InstanceId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="mealId">Initial value of the MealId property.</param>
        /// <param name="mealDate">Initial value of the MealDate property.</param>
        public static MealPlanList CreateMealPlanList(global::System.Int32 instanceId, global::System.Int32 userId, global::System.Int32 mealId, global::System.DateTime mealDate)
        {
            MealPlanList mealPlanList = new MealPlanList();
            mealPlanList.InstanceId = instanceId;
            mealPlanList.UserId = userId;
            mealPlanList.MealId = mealId;
            mealPlanList.MealDate = mealDate;
            return mealPlanList;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InstanceId
        {
            get
            {
                return _InstanceId;
            }
            set
            {
                if (_InstanceId != value)
                {
                    OnInstanceIdChanging(value);
                    ReportPropertyChanging("InstanceId");
                    _InstanceId = StructuralObject.SetValidValue(value, "InstanceId");
                    ReportPropertyChanged("InstanceId");
                    OnInstanceIdChanged();
                }
            }
        }
        private global::System.Int32 _InstanceId;
        partial void OnInstanceIdChanging(global::System.Int32 value);
        partial void OnInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MealId
        {
            get
            {
                return _MealId;
            }
            set
            {
                OnMealIdChanging(value);
                ReportPropertyChanging("MealId");
                _MealId = StructuralObject.SetValidValue(value, "MealId");
                ReportPropertyChanged("MealId");
                OnMealIdChanged();
            }
        }
        private global::System.Int32 _MealId;
        partial void OnMealIdChanging(global::System.Int32 value);
        partial void OnMealIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MealDate
        {
            get
            {
                return _MealDate;
            }
            set
            {
                OnMealDateChanging(value);
                ReportPropertyChanging("MealDate");
                _MealDate = StructuralObject.SetValidValue(value, "MealDate");
                ReportPropertyChanged("MealDate");
                OnMealDateChanged();
            }
        }
        private global::System.DateTime _MealDate;
        partial void OnMealDateChanging(global::System.DateTime value);
        partial void OnMealDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodModel", "FK_Users_MealPlanList", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("foodModel.FK_Users_MealPlanList", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("foodModel.FK_Users_MealPlanList", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("foodModel.FK_Users_MealPlanList", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("foodModel.FK_Users_MealPlanList", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="dateJoined">Initial value of the DateJoined property.</param>
        public static User CreateUser(global::System.Int32 userId, global::System.String userName, global::System.DateTime dateJoined)
        {
            User user = new User();
            user.UserId = userId;
            user.UserName = userName;
            user.DateJoined = dateJoined;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value, "LastLogin");
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLogin;
        partial void OnLastLoginChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateJoined
        {
            get
            {
                return _DateJoined;
            }
            set
            {
                OnDateJoinedChanging(value);
                ReportPropertyChanging("DateJoined");
                _DateJoined = StructuralObject.SetValidValue(value, "DateJoined");
                ReportPropertyChanged("DateJoined");
                OnDateJoinedChanged();
            }
        }
        private global::System.DateTime _DateJoined;
        partial void OnDateJoinedChanging(global::System.DateTime value);
        partial void OnDateJoinedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value, "DOB");
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodModel", "FK_Users_MealPlanList", "MealPlanList")]
        public EntityCollection<MealPlanList> MealPlanLists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MealPlanList>("foodModel.FK_Users_MealPlanList", "MealPlanList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MealPlanList>("foodModel.FK_Users_MealPlanList", "MealPlanList", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodModel", "FK_Users_Meals", "Meals")]
        public EntityCollection<Meal> Meals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Meal>("foodModel.FK_Users_Meals", "Meals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Meal>("foodModel.FK_Users_Meals", "Meals", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
