<%@ Page MaintainScrollPositionOnPostback="true" Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" Inherits="Admin_Users" Codebehind="Users.aspx.cs" %>


<asp:Content ID="Content1" ContentPlaceHolderID="contentMain" runat="Server">
    <div style="font-size: x-small">
        <table style="width: 100%">
            <tr style="vertical-align: top;">
                <td>
        <asp:GridView HorizontalAlign="Right" ID="gridUsers" DataKeyNames="UserId" runat="server" AutoGenerateColumns="False" DataSourceID="dataSourceUsers" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
                <asp:BoundField DataField="LastLogin" HeaderText="LastLogin" SortExpression="LastLogin" />
                <asp:BoundField DataField="DateJoined" HeaderText="DateJoined" SortExpression="DateJoined" />
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="False" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
                </td>
                <td>
        <asp:DetailsView OnDataBound="detailsUsers_DataBound" ID="detailsUsers" runat="server" Height="50px"
            AutoGenerateRows="False" DataKeyNames="UserId" DataSourceID="dataSourceUserDetails"
            OnItemDeleted="detailsUsers_ItemDeleted" OnItemInserted="Update" OnItemUpdated="Update" HeaderText="User details"
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" 
            BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" 
            ForeColor="Black" GridLines="Vertical" Width="250px" OnItemDeleting="detailsUsers_ItemDeleting">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <EditRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <Fields>
                <asp:TemplateField Visible="false">
                    <ItemTemplate>
                        <asp:Label ID="lblUserId" runat="server" Text='<%# Bind("UserId") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
                <asp:BoundField DataField="LastLogin" HeaderText="LastLogin" SortExpression="LastLogin" />
                <asp:BoundField DataField="DateJoined" HeaderText="DateJoined" SortExpression="DateJoined" />
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
            </Fields>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        </asp:DetailsView>
                </td>
            </tr>
        </table>
        <asp:EntityDataSource ID="dataSourceUsers" runat="server" ConnectionString="name=foodEntities" DefaultContainerName="foodEntities" EnableFlattening="False" EntitySetName="Users"></asp:EntityDataSource>
        <asp:EntityDataSource ID="dataSourceUserDetails" runat="server"
            ConnectionString="name=foodEntities"
            DefaultContainerName="foodEntities"
            Select=""
            Where="it.UserId == @UserId"
            EnableDelete="True" EnableFlattening="False" EnableInsert="True" EnableUpdate="True"
            EntitySetName="Users">
            <WhereParameters>
                <asp:ControlParameter ControlID="gridUsers" Name="UserId" Type="Int32" PropertyName="SelectedValue" />
            </WhereParameters>
        </asp:EntityDataSource>
    </div>
</asp:Content>

